const express = require('express');
const path = require('path');
const ejs = require("ejs");
require('dotenv').config()
const app = express();

const urlRoutes = require('./routes/url');
const staticRoutes = require('./routes/staticRoute');
const  {connectToMongoDb} = require('./config/dbConnect');
const URL = require('./models/url');


connectToMongoDb('mongodb://127.0.0.1:27017/shortend-url')
.then(() => console.log('MongoDb connected'))
.catch((err) => console.log("Something went wrong while connecting db", err))

app.set('view engine', 'ejs');
app.set('views', path.resolve("./views"));

app.use(express.json());
app.use(express.urlencoded({extended: false}))

// This middleware function is part of the express framework.
// It parses incoming requests with URL-encoded payloads. These are typically generated by HTML forms with the POST method.


app.use('/url', urlRoutes);

// SSR - server side rendering

app.use('/', staticRoutes)

// app.use('/test', async (req, res) => {

//     const allUrls = await URL.find({})
//     console.log(allUrls)

//    return res.render('home', {
//         urls: allUrls
//     })
// })

const PORT = process.env.PORT;

app.listen(PORT, () => {console.log(`Server started at ${PORT}`)})